name 'hello_world_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hello_world_server'
long_description 'Installs/Configures hello_world_server'
version '0.1.0'
